package org.staticcollective.gro.crossing

import org.erdtman.jcs.JsonCanonicalizer
import org.json.JSONArray
import org.json.JSONObject
import java.math.BigInteger
import java.nio.charset.StandardCharsets
import java.security.AlgorithmParameters
import java.security.KeyFactory
import java.security.MessageDigest
import java.security.Signature
import java.security.spec.ECGenParameterSpec
import java.security.spec.ECPoint
import java.security.spec.ECPublicKeySpec
import java.security.spec.ECParameterSpec
import java.util.Base64

/**
 * Verifies reLATTE's CrossingEnvelope v0 exactly as a signed crossing.
 * Deliberately has NO receive/admit/effect API.
 *
 * Ported from reLATTE src/protocol.ts: JCS domain separated P-256 signatures
 * generated by WebCrypto in raw IEEE-P1363 (r || s) format.
 */
object CrossingVerifier {
    private const val ID_DOMAIN = "reLATTE-CrossingEnvelope-v0|"
    private const val SIGN_DOMAIN = "reLATTE-CrossingSignature-v0|"
    private const val MAX_BYTES = 256 * 1024
    private val timestamp = Regex("""\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{3})?Z""")
    private val allowed = setOf(
        "schema", "crossing_id", "protocol_version", "source_particular",
        "source_world", "source_history_head", "parents", "declared_kind",
        "payload_refs", "requested_effect", "capability_ref", "privacy_policy",
        "audience_policy", "return_address", "created_at", "signing", "extensions",
    )

    data class Verified(val crossingId: String, val canonicalHash: String, val canonicalBytes: ByteArray)

    fun sha256(bytes: ByteArray): String = MessageDigest.getInstance("SHA-256")
        .digest(bytes).joinToString("") { "%02x".format(it.toInt() and 0xff) }

    private fun jcs(obj: JSONObject): String = JsonCanonicalizer(obj.toString()).encodedString

    private fun required(obj: JSONObject, name: String): String =
        obj.getString(name).also { require(it.isNotBlank() && !obj.isNull(name)) { "Invalid $name" } }

    private fun requiredArray(obj: JSONObject, name: String): JSONArray =
        obj.getJSONArray(name)

    private fun normalized(obj: JSONObject, name: String): Any =
        if (obj.has(name)) obj.get(name) else JSONObject.NULL

    private fun base64UrlExact(s: String, length: Int): ByteArray {
        require(Regex("[A-Za-z0-9_-]+").matches(s)) { "Invalid base64url alphabet" }
        val bytes = Base64.getUrlDecoder().decode(s)
        require(bytes.size == length && Base64.getUrlEncoder().withoutPadding().encodeToString(bytes) == s) {
            "Invalid base64url size/canonicality"
        }
        return bytes
    }

    private fun derInteger(bytes: ByteArray): ByteArray = BigInteger(1, bytes).toByteArray()
    private fun p1363ToDer(raw: ByteArray): ByteArray {
        require(raw.size == 64) { "Expected WebCrypto P256 raw signature" }
        val r = derInteger(raw.copyOfRange(0,32))
        val s = derInteger(raw.copyOfRange(32,64))
        val size = 2+r.size+2+s.size
        require(size < 128)
        return byteArrayOf(0x30,size.toByte(),0x02,r.size.toByte()) + r +
            byteArrayOf(0x02,s.size.toByte()) + s
    }

    fun verify(raw: ByteArray): Verified {
        require(raw.isNotEmpty() && raw.size <= MAX_BYTES) { "Crossing too large" }
        val text = raw.toString(StandardCharsets.UTF_8)
        require(text.toByteArray(StandardCharsets.UTF_8).contentEquals(raw)) { "Invalid UTF-8" }
        // Canonicalize original JSON to validate input syntax and bound duplicate-key ambiguity.
        val originalCanonical = JsonCanonicalizer(text).encodedString
        val root = JSONObject(originalCanonical)
        val names = mutableSetOf<String>()
        val keys = root.keys()
        while (keys.hasNext()) names.add(keys.next())
        require(names.all { it in allowed }) { "Unexpected envelope fields" }
        require(required(root,"schema") == "relatte.crossing-envelope/v0")
        require(required(root,"protocol_version") == "0")
        val created = required(root,"created_at")
        require(timestamp.matches(created)) { "Invalid timestamp" }

        val signing = root.getJSONObject("signing")
        require(signing.length() == 4)
        require(required(signing,"algorithm") == "ECDSA-P256-SHA256")
        require(required(signing,"domain") == "relatte.crossing-signature/v0")
        val pub = signing.getJSONObject("public_key")
        require(!pub.has("d"))
        require(required(pub,"kty") == "EC" && required(pub,"crv") == "P-256")
        val x = base64UrlExact(required(pub,"x"),32)
        val y = base64UrlExact(required(pub,"y"),32)
        val signature = base64UrlExact(required(signing,"signature"),64)
        val normalizedPub = JSONObject()
            .put("kty","EC").put("crv","P-256")
            .put("x",required(pub,"x")).put("y",required(pub,"y"))
        val signingBody = JSONObject()
            .put("algorithm","ECDSA-P256-SHA256")
            .put("public_key",normalizedPub)
            .put("domain","relatte.crossing-signature/v0")
        val body = JSONObject()
            .put("schema","relatte.crossing-envelope/v0")
            .put("protocol_version","0")
            .put("source_particular",required(root,"source_particular"))
            .put("source_world",required(root,"source_world"))
            .put("source_history_head",normalized(root,"source_history_head"))
            .put("parents", if(root.has("parents")) root.getJSONArray("parents") else JSONArray())
            .put("declared_kind",required(root,"declared_kind"))
            .put("payload_refs",requiredArray(root,"payload_refs"))
            .put("requested_effect",normalized(root,"requested_effect"))
            .put("capability_ref",normalized(root,"capability_ref"))
            .put("privacy_policy",normalized(root,"privacy_policy"))
            .put("audience_policy",normalized(root,"audience_policy"))
            .put("return_address",normalized(root,"return_address"))
            .put("created_at",created)
            .put("signing",signingBody)
            .put("extensions",if(root.has("extensions")) root.getJSONObject("extensions") else JSONObject())
        val crossingId = "relatte-crossing-v0:" + sha256(
            (ID_DOMAIN + jcs(body)).toByteArray(StandardCharsets.UTF_8),
        )
        require(required(root,"crossing_id") == crossingId) { "Crossing ID mismatch" }
        body.put("crossing_id",crossingId)

        val parameters = AlgorithmParameters.getInstance("EC")
        parameters.init(ECGenParameterSpec("secp256r1"))
        val curve = parameters.getParameterSpec(ECParameterSpec::class.java)
        val keySpec = ECPublicKeySpec(ECPoint(BigInteger(1,x),BigInteger(1,y)),curve)
        val pubKey = KeyFactory.getInstance("EC").generatePublic(keySpec)
        val verifier = Signature.getInstance("SHA256withECDSA")
        verifier.initVerify(pubKey)
        verifier.update((SIGN_DOMAIN + jcs(body)).toByteArray(StandardCharsets.UTF_8))
        require(verifier.verify(p1363ToDer(signature))) { "P256 crossing signature invalid" }

        return Verified(crossingId, sha256(raw),raw.copyOf())
    }
}
